from __future__ import annotations

def generate():
    for o in dir(dsviper):
        s = str(o)
        if not s.startswith("_"):
            print(f'#{s}(')


#generate()
#Attachment(    
#AttachmentFunctionPool(
#AttachmentFunctionPoolFunctions(
#AttachmentGetting(
#AttachmentGettingFunction(
#AttachmentMutating(
#AttachmentMutatingFunction(
#BlobArray(
#BlobData(
#BlobEncoder(
#BlobEncoderLayout(
#BlobGetting(
#BlobIdMapper(
#BlobInfo(
#BlobLayout(
#BlobPack(
#BlobPackDescriptor(
#BlobPackRegion(
#BlobStatistics(
#BlobStream(
#BlobView(
#Cancelation(
#Codec(
#Commit(
#CommitAction(
#CommitData(
#CommitDatabase(
#CommitDatabaseRemote(
#CommitDatabaseSQLite(
#CommitDatabaseServer(
#CommitDatabasing(
#CommitEvalAction(
#CommitHeader(
#CommitMutableState(
#CommitNode(
#CommitNodeGrid(
#CommitNodeGridBuilder(
#CommitState(
#CommitStore(
#CommitStoreBaseNotifying(
#CommitSyncData(
#CommitSynchronizer(
#CommitSynchronizerInfo(
#CommitSynchronizerInfoTransmit(
#DSMAttachment(
#DSMAttachmentFunction(
#DSMAttachmentFunctionPool(
#DSMBuilder(
#DSMBuilderPart(
#DSMClub(
#DSMConcept(
#DSMDefinitions(
#DSMDefinitionsInspector(
#DSMEnumeration(
#DSMEnumerationCase(
#DSMFunction(
#DSMFunctionPool(
#DSMFunctionPrototype(
#DSMLiteralList(
#DSMLiteralValue(
#DSMParseError(
#DSMParseReport(
#DSMStructure(
#DSMStructureField(
#DSMTypeKey(
#DSMTypeMap(
#DSMTypeMat(
#DSMTypeOptional(
#DSMTypeReference(
#DSMTypeSet(
#DSMTypeTuple(
#DSMTypeVariant(
#DSMTypeVec(
#DSMTypeVector(
#DSMTypeXArray(
#Database(
#DatabaseRemote(
#DatabaseSQLite(
#Databasing(
#Definitions(
#DefinitionsCollector(
#DefinitionsConst(
#DefinitionsExtendInfo(
#DefinitionsInspector(
#DefinitionsMapper(
#DocumentNode(
#Error(
#Float16(
#Function(
#FunctionPool(
#FunctionPoolFunctions(
#FunctionPrototype(
#Fuzzer(
#HashCRC32(
#HashMD5(
#HashSHA1(
#HashSHA256(
#HashSHA3(
#Hashing(
#Html(
#KeyHelper(
#KeyNamer(
#LoggerConsole(
#LoggerNull(
#LoggerPrint(
#LoggerReport(
#Logging(
#NameSpace(
#Path(
#PathComponent(
#PathConst(
#PathElementInfo(
#PathEntryKeyInfo(
#SQLite(
#Semaphore(
#ServiceRemote(
#ServiceRemoteAttachmentFunction(
#ServiceRemoteAttachmentFunctionPool(
#ServiceRemoteAttachmentFunctionPoolFunction(
#ServiceRemoteAttachmentFunctionPoolFunctions(
#ServiceRemoteAttachmentFunctionPools(
#ServiceRemoteFunction(
#ServiceRemoteFunctionPool(
#ServiceRemoteFunctionPoolFunction(
#ServiceRemoteFunctionPoolFunctions(
#ServiceRemoteFunctionPools(
#SharedMemory(
#Socket(
#StreamBinaryReader(
#StreamBinaryWriter(
#StreamCodecInstancing(
#StreamDecoding(
#StreamEncoding(
#StreamRawReader(
#StreamRawReading(
#StreamRawWriter(
#StreamRawWriting(
#StreamReaderBlob(
#StreamReaderFile(
#StreamReaderSharedMemory(
#StreamReading(
#StreamSizing(
#StreamTokenBinaryReader(
#StreamTokenBinaryWriter(
#StreamWriterBlob(
#StreamWriterFile(
#StreamWriterSharedMemory(
#StreamWriting(
#Type(
#TypeAny(
#TypeAnyConcept(
#TypeBlob(
#TypeBlobId(
#TypeBool(
#TypeClub(
#TypeCommitId(
#TypeConcept(
#TypeDouble(
#TypeEnumeration(
#TypeEnumerationCase(
#TypeEnumerationDescriptor(
#TypeFloat(
#TypeInt16(
#TypeInt32(
#TypeInt64(
#TypeInt8(
#TypeKey(
#TypeMap(
#TypeMat(
#TypeName(
#TypeOptional(
#TypeSet(
#TypeString(
#TypeStructure(
#TypeStructureDescriptor(
#TypeStructureField(
#TypeTuple(
#TypeUInt16(
#TypeUInt32(
#TypeUInt64(
#TypeUInt8(
#TypeUUId(
#TypeVariant(
#TypeVec(
#TypeVector(
#TypeVoid(
#TypeXArray(
#Value(
#ValueAny(
#ValueBlob(
#ValueBlobId(
#ValueBool(
#ValueCommitId(
#ValueDouble(
#ValueEnumeration(
#ValueFloat(
#ValueInt16(
#ValueInt32(
#ValueInt64(
#ValueInt8(
#ValueKey(
#ValueMap(
#ValueMapItemsIter(
#ValueMapKeysIter(
#ValueMapValuesIter(
#ValueMat(
#ValueOpcodeDocumentSet(
#ValueOpcodeDocumentUpdate(
#ValueOpcodeKey(
#ValueOpcodeMapSubtract(
#ValueOpcodeMapUnion(
#ValueOpcodeMapUpdate(
#ValueOpcodeSetSubtract(
#ValueOpcodeSetUnion(
#ValueOpcodeXArrayInsert(
#ValueOpcodeXArrayRemove(
#ValueOpcodeXArrayUpdate(
#ValueOptional(
#ValueProgram(
#ValueSet(
#ValueSetIter(
#ValueString(
#ValueStructure(
#ValueTuple(
#ValueTupleIter(
#ValueUInt16(
#ValueUInt32(
#ValueUInt64(
#ValueUInt8(
#ValueUUId(
#ValueVariant(
#ValueVec(
#ValueVector(
#ValueVectorIter(
#ValueVoid(
#ValueXArray(
#ViperError(
#version(
